name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow triggering manually.
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  with_default_features:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.88.0, stable, beta]
    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}

    - name: Clippy
      if: matrix.rust == 'stable'
      run: cargo clippy ${{ matrix.args }} --all-targets --verbose

    - name: Run tests
      run: cargo test --all-targets --verbose

  with_extra_features:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]
        args: [
          "--features tls-with-openssl --example demo",
          "--features tls-with-rustls --example demo",
          "--no-default-features --features sync",
          "--no-default-features --features async-with-tokio",
          "--no-default-features --example demo --features tls-with-openssl",
          "--no-default-features --example demo --features tls-with-rustls",
          "--no-default-features --example demo --features tls-with-tokio-native-tls",
          "--no-default-features --example demo --features tls-with-tokio-rustls",
        ]
    steps:
    - uses: actions/checkout@v3

    - name: Clippy
      if: matrix.rust == 'stable'
      run: cargo clippy ${{ matrix.args }} --all-targets --verbose

    - name: Run tests
      run: cargo test ${{ matrix.args }} --all-targets --verbose
